# Generated by Django 5.1.1 on 2024-09-28 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveSmallIntegerField(null=True)),
                ('gender', models.CharField(max_length=20, null=True)),
                ('symptoms', models.CharField(max_length=500, null=True)),
                ('history', models.CharField(max_length=500, null=True)),
                ('family', models.CharField(max_length=500, null=True)),
                ('lifestyle', models.CharField(max_length=500, null=True)),
                ('tests', models.CharField(max_length=500, null=True)),
                ('other', models.CharField(max_length=500, null=True)),
                ('log_date', models.DateTimeField(verbose_name='date logged')),
            ],
        ),
    ]
