# Generated by Django 5.1.1 on 2024-09-29 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_specialist_experience_specialist_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialist',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='specialist',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='specialist',
            name='location',
        ),
        migrations.AddField(
            model_name='specialist',
            name='available_day',
            field=models.CharField(default='Monday', max_length=100),
        ),
        migrations.AddField(
            model_name='specialist',
            name='phone',
            field=models.CharField(default='000-000-0000', max_length=15),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='specialty',
            field=models.CharField(max_length=100),
        ),
    ]
